import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Legacy shadcn colors
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "#ef4e30",
          foreground: "#ffffff",
        },
        secondary: {
          DEFAULT: "#506071",
          foreground: "#ffffff",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        // Q-CHANG Design System Colors
        "brand-blue": "#0e1f2e",
        "on-primary": "#ffffff",
        "surface-container": "#edeeef",
        "on-secondary-container": "#566678",
        "inverse-on-surface": "#f0f1f2",
        "secondary-container": "#d3e4f9",
        "surface-bg": "#f8f9fa",
        outline: "#8f706a",
        "surface-container-highest": "#e1e3e4",
        tertiary: "#595c5d",
        "on-primary-fixed": "#3e0400",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#fbfdfe",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#727576",
        "on-surface": "#191c1d",
        "primary-fixed": "#ffdad3",
        "outline-variant": "#e3beb7",
        "on-secondary": "#ffffff",
        "surface-bright": "#f8f9fa",
        "on-surface-variant": "#5b403b",
        "surface-container-high": "#e7e8e9",
        "on-error": "#ffffff",
        "on-background": "#191c1d",
        "primary-fixed-dim": "#ffb4a5",
        "on-primary-container": "#fffbff",
        "error-container": "#ffdad6",
        "surface-variant": "#e1e3e4",
        "surface-dim": "#d9dadb",
        "inverse-primary": "#ffb4a5",
        "surface-tint": "#b6250a",
        surface: "#f8f9fa",
        error: "#ba1a1a",
        "inverse-surface": "#2e3132",
        "primary-container": "#ef4e30",
        "secondary-fixed": "#d3e4f9",
        "surface-container-low": "#f3f4f5",
        "success-container": "#d1fae5",
        "on-success-container": "#065f46",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xl: "0.75rem",
        "2xl": "1.5rem",
        "3xl": "1.5rem",
      },
      spacing: {
        "stack-md": "1rem",
        "stack-lg": "2rem",
        "stack-sm": "0.5rem",
        gutter: "1rem",
        "card-gap": "1rem",
        "container-padding": "1.25rem",
      },
      fontFamily: {
        prompt: ["var(--font-prompt)", "Prompt", "sans-serif"],
        sarabun: ["var(--font-sarabun)", "Sarabun", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
      },
      boxShadow: {
        "level-1": "0px 4px 20px rgba(14, 31, 46, 0.06)",
        "level-2": "0px 12px 32px rgba(14, 31, 46, 0.12)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
